In [14]:
import pyodbc

conn = pyodbc.connect(                         
    "driver={ODBC Driver 17 for SQL Server};"
    "server=localhost\\SQLEXPRESS;"
    "database=ETL_Sales;"
    "trusted_connection=yes;" 
)

cursor = conn.cursor()

In [15]:
import pandas as pd
df = pd.read_csv('sales.csv')
df

   order_id      customer     product  quantity  unit_price  total_amount
0      1001  Ahmed Hassan      Laptop         2       25000         50000
1      1002      Sara Ali       Mouse         1         500           500
2      1003  Omar Mohamed    Keyboard         3        1200          3600
3      1004  Mona Ibrahim      Laptop         1       25000         25000
4      1005  Ahmed Hassan     Monitor         2        7000         14000
5      1006  Ahmed Hassan       Mouse         1         500           500
6      1007      Sara Ali  Headphones         4        2500         10000
7      1008  Omar Mohamed      Laptop         1       25000         25000
8      1009  Mona Ibrahim    Keyboard         2        1200          2400
9      1010  Ahmed Hassan     Monitor         1        7000          7000

In [16]:
cursor.execute( """
IF OBJECT_ID('Sales', 'U') IS NOT NULL DROP TABLE Sales;
CREATE TABLE Sales (
    order_id INT,
    customer VARCHAR(50),
    product VARCHAR(50),
    quantity INT,
    unit_price FLOAT,
    total_amount FLOAT 
)
""")

In [17]:
sales_list = df.values.tolist()
sales_list

[[1001, 'Ahmed Hassan', 'Laptop', 2, 25000, 50000],
 [1002, 'Sara Ali', 'Mouse', 1, 500, 500],
 [1003, 'Omar Mohamed', 'Keyboard', 3, 1200, 3600],
 [1004, 'Mona Ibrahim', 'Laptop', 1, 25000, 25000],
 [1005, 'Ahmed Hassan', 'Monitor', 2, 7000, 14000],
 [1006, 'Ahmed Hassan', 'Mouse', 1, 500, 500],
 [1007, 'Sara Ali', 'Headphones', 4, 2500, 10000],
 [1008, 'Omar Mohamed', 'Laptop', 1, 25000, 25000],
 [1009, 'Mona Ibrahim', 'Keyboard', 2, 1200, 2400],
 [1010, 'Ahmed Hassan', 'Monitor', 1, 7000, 7000]]

In [18]:
cursor.executemany(
    "INSERT INTO Sales VALUES (?,?,?,?,?,?)",
    sales_list
)

conn.commit()

In [19]:
df = pd.read_sql_query('SELECT * FROM Sales', conn)

df

C:\Users\zeina\AppData\Local\Temp\ipykernel_4496\1387627486.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql_query('SELECT * FROM Sales', conn)

   order_id      customer     product  quantity  unit_price  total_amount
0      1001  Ahmed Hassan      Laptop         2     25000.0       50000.0
1      1002      Sara Ali       Mouse         1       500.0         500.0
2      1003  Omar Mohamed    Keyboard         3      1200.0        3600.0
3      1004  Mona Ibrahim      Laptop         1     25000.0       25000.0
4      1005  Ahmed Hassan     Monitor         2      7000.0       14000.0
5      1006  Ahmed Hassan       Mouse         1       500.0         500.0
6      1007      Sara Ali  Headphones         4      2500.0       10000.0
7      1008  Omar Mohamed      Laptop         1     25000.0       25000.0
8      1009  Mona Ibrahim    Keyboard         2      1200.0        2400.0
9      1010  Ahmed Hassan     Monitor         1      7000.0        7000.0

In [20]:
cursor.close()
conn.close()